### DISCUSSION TITLE
Thermostat control

### DISCUSSION THREAD

**Discussion by xHirscHx** [HASwitchPlate/HASPone#10] [General]
Great work I really like how you cleaned everything up My automation section loves you for that , it's a lot easier to find things now.. My main use of the plate was to control the heating panels i have in every room. Im a little stuck trying to get that part  up and running. Also How to toggle group.
Once again great work.

**Comment by aderusha** [comment]
Can you tell us a little more about your heating panels?  What kind of controls do they have, how were they setup before, maybe how do you think you’d like the interaction to work?

**Comment by xHirscHx** [comment]
Its  i virtual thermostat through smartthings. I used the hvac.yaml with the old setup and modified some settings.

**Comment by xHirscHx** [comment]
The smartthings device handler uses the switch(tasmota sonoff th) that the heating panel is on with 3 temp sensors in the room. I get room temp heating temp,  set heating temp   and can set low temp.  I can switch to a local thermostat through home assistant. It was just easier to setup with the smartthings device.

**Comment by xHirscHx** [comment]
So by using the blueprint

HASP p[x].b[y] displays the current temperature with icon and colors
Im able to kinda get it working. Is there anyway  to get this blueprint to work on page  9

**Comment by IIAIronWolf** [comment]
That demo was really cool. Kinda sad to see them all gone now, though recreating your own is definitely much easier now.

**Comment by xHirscHx** [comment]
So i got  most of it thr hvac setup on page 9 currant temp ,temp, on/off, mode, outside temp, I just cant get it to increases +1 or decrease -1heating temp.
this is the old setup
  # Increment HVAC high temp set point when p[9].b[7] is pressed
  - alias: hasp_cjs_plate_p9_SetHVACTempHighPlus
    trigger:
      - platform: mqtt
        topic: "hasp/cjs_plate/state/p[9].b[7]"
        payload: "ON"
    action:
      - service: climate.set_temperature
        entity_id: "climate.cjs_thermostat"
        data_template:
          temperature: '{{ state_attr("climate.cjs_thermostat", "temperature") + 1 | int}}'


  # Decrement HVAC high temp set point when p[9].b[8] is pressed
  - alias: hasp_cjs_plate_p9_SetHVACTempHighMinus
    trigger:
      - platform: mqtt
        topic: "hasp/cjs_plate/state/p[9].b[8]"
        payload: "ON"
    action:
      - service: climate.set_temperature
        entity_id: "climate.cjs_thermostat"
        data_template:
          temperature: '{{ state_attr("climate.cjs_thermostat", "temperature") - 1 | int}}'

how do I  swap this over to blueprint. I've tried I few things but can only set a specific temp not increase it incrementally .

**Reply by mattthhdp** [reply]
this is what i have (but 0.5 instead of 1
so should be almost the same !

```
# Display current HVAC low temp set point on HASP when updated in Home Assistant
  - alias: hasp_plate01_p9_UpdateHVACTempLow
    trigger:
      platform: state
      entity_id: "climate.salon_chauffage"
    condition:
      condition: template
      value_template: '{{ trigger.from_state and trigger.to_state.attributes.target_temp_low != trigger.from_state.attributes.target_temp_low }}'
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/plate01/command/p[9].b[12].txt"
          payload_template: '" {{ state_attr("climate.salon_chauffage", "target_temp_low") }}°"'

  # Increment HVAC high temp set point when p[9].b[7] is pressed
  - alias: hasp_plate01_p9_SetHVACTempHighPlus
    trigger:
      - platform: mqtt
        topic: "hasp/plate01/state/p[9].b[7]"
        payload: "ON"
    action:
      - service: climate.set_temperature
        entity_id: "climate.salon_chauffage"
        data_template:
          temperature: '{{ state_attr("climate.salon_chauffage", "temperature") + 0.5 | float}}'
```
