### DISCUSSION TITLE
Older version code not working - please help!

### DISCUSSION THREAD

**Discussion by giovi321** [HASwitchPlate/HASPone#163] [Q&A]
Hi all,
I am using an older version of HASPone because it is horizontal (European standard box) and it would be very painful to rewrite HASPone to be horizontal in the new version.
I have another HASPone with exactly the same configuration that is running since more than a year perfectly, but with this one I am only able to show the first label on the first p[1]b[1]. What am I doing wrong, please?

This is my code for the file `hasp_displ_entrance_p0_pages.yaml`:

```
##############################################################################
# Automations for handling the 3 page select buttons at the bottom of each
# page on the panel.

automation:
##############################################################################
# Restore saved page on connect
  - alias: hasp_displ_entrance_p0_RestoreActivePage
    trigger:
    - platform: state
      entity_id: 'binary_sensor.displ_entrance_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/displ_entrance/command/page'
        payload_template: '{{states.input_number.hasp_displ_entrance_activepage.state|int}}'

##############################################################################
# select hasp_displ_entrance_pagebutton1page in response to page button 1
  - alias: hasp_displ_entrance_p0_PageButton1Action
    trigger:
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[1].b[1]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[2].b[1]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[3].b[1]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[4].b[1]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[5].b[1]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[6].b[1]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[7].b[1]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[8].b[1]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[9].b[1]'
      payload: 'ON'
    action:
    - service: input_number.set_value
      data_template:
        entity_id: 'input_number.hasp_displ_entrance_activepage'
        value: '{{states.input_number.hasp_displ_entrance_pagebutton1page.state|int}}'
      
##############################################################################
# select hasp_displ_entrance_pagebutton2page in response to page button 2
  - alias: hasp_displ_entrance_p0_PageButton2Action
    trigger:
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[1].b[2]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[2].b[2]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[3].b[2]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[4].b[2]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[5].b[2]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[6].b[2]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[7].b[2]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[8].b[2]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[9].b[2]'
      payload: 'ON'
    action:
    - service: input_number.set_value
      data_template:
        entity_id: 'input_number.hasp_displ_entrance_activepage'
        value: '{{states.input_number.hasp_displ_entrance_pagebutton2page.state|int}}'
      
##############################################################################
# select hasp_displ_entrance_pagebutton3page in response to page button 3
  - alias: hasp_displ_entrance_p0_PageButton3Action
    trigger:
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[1].b[3]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[2].b[3]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[3].b[3]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[4].b[3]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[5].b[3]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[6].b[3]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[7].b[3]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[8].b[3]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[9].b[3]'
      payload: 'ON'
    action:
    - service: input_number.set_value
      data_template:
        entity_id: 'input_number.hasp_displ_entrance_activepage'
        value: '{{states.input_number.hasp_displ_entrance_pagebutton3page.state|int}}'

##############################################################################
# select hasp_displ_entrance_pagebutton4page in response to page button 4
  - alias: hasp_displ_entrance_p0_PageButton4Action
    trigger:
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[1].b[4]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[2].b[4]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[3].b[4]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[4].b[4]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[5].b[4]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[6].b[4]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[7].b[4]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[8].b[4]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[9].b[4]'
      payload: 'ON'
    action:
    - service: input_number.set_value
      data_template:
        entity_id: 'input_number.hasp_displ_entrance_activepage'
        value: '{{states.input_number.hasp_displ_entrance_pagebutton4page.state|int}}'

##############################################################################
# select hasp_displ_entrance_pagebutton4page in response to page button 4 - alternative page
  - alias: hasp_displ_entrance_p0_PageButton4ActionAlternative
    trigger:
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/p[5].b[4]'
      payload: 'ON'
    action:
    - service: input_number.set_value
      data_template:
        entity_id: 'input_number.hasp_displ_entrance_activepage'
        value: '{{states.input_number.hasp_displ_entrance_pagebutton4page.state|int}}'

##############################################################################
# Update hasp_displ_entrance_p0_active_page when changed at the panel
  - alias: hasp_displ_entrance_p0_PanelPageChanged
    trigger:
    - platform: mqtt
      topic: 'hasp/displ_entrance/state/page'
    action:
    - service: automation.turn_off
      entity_id: automation.hasp_displ_entrance_p0_ActivePageSliderChanged
    - service: input_number.set_value
      data_template:
        entity_id: input_number.hasp_displ_entrance_activepage
        value: '{{ trigger.payload }}'
    - service: automation.turn_on
      entity_id: automation.hasp_displ_entrance_p0_ActivePageSliderChanged

##############################################################################
# Change page at panel when hasp_displ_entrance_p0_active_page updated
  - alias: hasp_displ_entrance_p0_ActivePageSliderChanged
    trigger:
    - platform: state
      entity_id: input_number.hasp_displ_entrance_activepage
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/displ_entrance/command/page'
        payload: '{{ states.input_number.hasp_displ_entrance_activepage.state|int }}'
      
##############################################################################
# Set page button text across all pages to the value selected in the interface

# set page button text on each page to hasp-displ_entrance-PageButton1Label
  - alias: hasp_displ_entrance_p0_PageButton1_Text
    trigger:
    - platform: state
      entity_id: input_text.hasp_displ_entrance_pagebutton1label
    - platform: state
      entity_id: 'binary_sensor.displ_entrance_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/displ_entrance/command/json'
        payload_template: >-
          [{%- for i in range(1,10) -%}"p[{{i}}].b[1].txt=\"{{states.input_text.hasp_displ_entrance_pagebutton1label.state}}\""{% if not loop.last %},{% endif %}{%- endfor -%}]

# set page button text on each page to hasp-displ_entrance-PageButton2Label
  - alias: hasp_displ_entrance_p0_PageButton2_Text
    trigger:
    - platform: state
      entity_id: input_text.hasp_displ_entrance_pagebutton2label
    - platform: state
      entity_id: 'binary_sensor.displ_entrance_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/displ_entrance/command/json'
        payload_template: >-
          [{%- for i in range(1,10) -%}"p[{{i}}].b[2].txt=\"{{states.input_text.hasp_displ_entrance_pagebutton2label.state}}\""{% if not loop.last %},{% endif %}{%- endfor -%}]

# set page button text on each page to hasp-displ_entrance-PageButton3Label
  - alias: hasp_displ_entrance_p0_PageButton3_Text
    trigger:
    - platform: state
      entity_id: input_text.hasp_displ_entrance_pagebutton3label
    - platform: state
      entity_id: 'binary_sensor.displ_entrance_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/displ_entrance/command/json'
        payload_template: >-
          [{%- for i in range(1,10) -%}"p[{{i}}].b[3].txt=\"{{states.input_text.hasp_displ_entrance_pagebutton3label.state}}\""{% if not loop.last %},{% endif %}{%- endfor -%}]

# set page button text on each page to hasp-displ_entrance-PageButton4Label
  - alias: hasp_displ_entrance_p0_PageButton4_Text
    trigger:
    - platform: state
      entity_id: input_text.hasp_displ_entrance_pagebutton4label
    - platform: state
      entity_id: 'binary_sensor.displ_entrance_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/displ_entrance/command/json'
        payload_template: >-
          [{%- for i in range(1,10) -%}"p[{{i}}].b[4].txt=\"{{states.input_text.hasp_displ_entrance_pagebutton4label.state}}\""{% if not loop.last %},{% endif %}{%- endfor -%}]

##############################################################################
# Set page button colors across selected pages to show active page button
  - alias: hasp_displ_entrance_p0_PageButtonColors
    trigger:
    - platform: state
      entity_id: input_number.hasp_displ_entrance_pagebutton1page
    - platform: state
      entity_id: input_number.hasp_displ_entrance_pagebutton2page
    - platform: state
      entity_id: input_number.hasp_displ_entrance_pagebutton3page
    - platform: state
      entity_id: input_number.hasp_displ_entrance_pagebutton4page
    - platform: state
      entity_id: input_number.hasp_displ_entrance_pagebutton4page
    - platform: state
      entity_id: input_number.hasp_displ_entrance_selectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_displ_entrance_unselectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_displ_entrance_selectedforegroundcolor
    - platform: state
      entity_id: input_number.hasp_displ_entrance_unselectedforegroundcolor
    - platform: state
      entity_id: 'binary_sensor.displ_entrance_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/displ_entrance/command/json'
        payload_template: >-
          [{%- for i in range(1,10) -%}"p[{{i}}].b[1].pco={% if i == states.input_number.hasp_displ_entrance_pagebutton1page.state|int -%}
              {{ states.input_number.hasp_displ_entrance_selectedforegroundcolor.state|int }}
            {%- else -%}
              {{ states.input_number.hasp_displ_entrance_unselectedforegroundcolor.state|int }}
            {%- endif %}",
          {%- endfor -%}
          {%- for i in range(1,10) -%}"p[{{i}}].b[1].bco={% if i == states.input_number.hasp_displ_entrance_pagebutton1page.state|int -%}
              {{ states.input_number.hasp_displ_entrance_selectedbackgroundcolor.state|int }}
            {%- else -%}
              {{ states.input_number.hasp_displ_entrance_unselectedbackgroundcolor.state|int }}
            {%- endif %}",
          {%- endfor -%}
          {%- for i in range(1,10) -%}"p[{{i}}].b[2].pco={% if i == states.input_number.hasp_displ_entrance_pagebutton2page.state|int -%}
              {{ states.input_number.hasp_displ_entrance_selectedforegroundcolor.state|int }}
            {%- else -%}
              {{ states.input_number.hasp_displ_entrance_unselectedforegroundcolor.state|int }}
            {%- endif %}",
          {%- endfor -%}
          {%- for i in range(1,10) -%}"p[{{i}}].b[2].bco={% if i == states.input_number.hasp_displ_entrance_pagebutton2page.state|int -%}
              {{ states.input_number.hasp_displ_entrance_selectedbackgroundcolor.state|int }}
            {%- else -%}
              {{ states.input_number.hasp_displ_entrance_unselectedbackgroundcolor.state|int }}
            {%- endif %}",
          {%- for i in range(1,10) -%}"p[{{i}}].b[3].pco={% if i == states.input_number.hasp_displ_entrance_pagebutton3page.state|int or i == states.input_number.hasp_displ_entrance_pagebutton3page.state|int -%}
              {{ states.input_number.hasp_displ_entrance_selectedforegroundcolor.state|int }}
            {%- else -%}
              {{ states.input_number.hasp_displ_entrance_unselectedforegroundcolor.state|int }}
            {%- endif %}",
          {%- endfor -%}
          {%- for i in range(1,10) -%}"p[{{i}}].b[3].bco={% if i == states.input_number.hasp_displ_entrance_pagebutton3page.state|int or i == states.input_number.hasp_displ_entrance_pagebutton3page.state|int -%}
              {{ states.input_number.hasp_displ_entrance_selectedbackgroundcolor.state|int }}
            {%- else -%}
              {{ states.input_number.hasp_displ_entrance_unselectedbackgroundcolor.state|int }}
            {%- endif %}",
          {%- endfor -%}
          {%- endfor -%}
          {%- for i in range(1,10) -%}"p[{{i}}].b[4].pco={% if i == states.input_number.hasp_displ_entrance_pagebutton4page.state|int -%}
              {{ states.input_number.hasp_displ_entrance_selectedforegroundcolor.state|int }}
            {%- else -%}
              {{ states.input_number.hasp_displ_entrance_unselectedforegroundcolor.state|int }}
            {%- endif %}",
          {%- endfor -%}
          {%- for i in range(1,10) -%}"p[{{i}}].b[4].bco={% if i == states.input_number.hasp_displ_entrance_pagebutton4page.state|int -%}
              {{ states.input_number.hasp_displ_hasp_displ_entrance_p0_pages.yamlentrance_selectedbackgroundcolor.state|int }}
            {%- else -%}
              {{ states.input_number.hasp_displ_entrance_unselectedbackgroundcolor.state|int }}
            {%- endif %}"{% if not loop.last %},{% endif %}
          {%- endfor -%}]
```

and this is `hasp_displ_entrance_00_components.yaml`

```
##############################################################################
# The devices created below are essential to the page control automations
# and you'll probably want to carry them over to your own configuration


# Enable this iframe to integrate the HASP web admin panel in Hass.
# This will not work if you have SSL enabled, see details here:
# https://www.home-assistant.io/components/panel_iframe/
#
panel_iframe:
  displ_entrance:
    title: "displ_entrance"
    url: "http://displ_entrance"
    icon: "mdi:cellphone-text"
    require_admin: true

light:
  - platform: mqtt
    name: displ_entrance Backlight
    command_topic: "hasp/displ_entrance/light/switch"
    state_topic: "hasp/displ_entrance/light/state"
    brightness_state_topic: "hasp/displ_entrance/brightness/state"
    brightness_command_topic: "hasp/displ_entrance/brightness/set"
    availability_topic: "hasp/displ_entrance/status"
    payload_available: "ON"
    payload_not_available: "OFF"

binary_sensor:
  - platform: mqtt
    name: displ_entrance Connected
    device_class: connectivity
    state_topic: "hasp/displ_entrance/status"
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: "hasp/displ_entrance/status"
    payload_available: "ON"
    payload_not_available: "OFF"

sensor:
  - platform: mqtt
    name: displ_entrance Status
    state_topic: "hasp/displ_entrance/status"
    availability_topic: "hasp/displ_entrance/status"
    payload_available: "ON"
    payload_not_available: "OFF"
    json_attributes_topic:  "hasp/displ_entrance/sensor"

input_text:
  hasp_displ_entrance_pagebutton1label:
    name: displ_entrance Page 1 Label
    icon: mdi:book-open-page-variant
  hasp_displ_entrance_pagebutton2label:
    name: displ_entrance Page 2 Label
    icon: mdi:book-open-page-variant
  hasp_displ_entrance_pagebutton3label:
    name: displ_entrance Page 3 Label
    icon: mdi:book-open-page-variant
  hasp_displ_entrance_pagebutton4label:
    name: displ_entrance Page 4 Label
    icon: mdi:book-open-page-variant

input_number:
  hasp_displ_entrance_pagebutton1page:
    name: displ_entrance Page 1 Page
    icon: mdi:numeric
    min: 0
    max: 9
    step: 1
  hasp_displ_entrance_pagebutton2page:
    name: displ_entrance Page 2 Page
    icon: mdi:numeric
    min: 0
    max: 9
    step: 1
  hasp_displ_entrance_pagebutton3page:
    name: displ_entrance Page 3 Page
    icon: mdi:numeric
    min: 0
    max: 9
    step: 1
  hasp_displ_entrance_pagebutton4page:
    name: displ_entrance Page 4 Page
    icon: mdi:numeric
    min: 0
    max: 9
    step: 1
  hasp_displ_entrance_pagebutton4page_alternative:
    name: displ_bedroom Page 4 alternative Page
    icon: mdi:numeric
    min: 0
    max: 9
    step: 1
  hasp_displ_entrance_activepage:
    name: displ_entrance Active Page
    icon: mdi:numeric
    min: 0
    max: 9
    step: 1
  hasp_displ_entrance_alarmcode1:
    name: displ_entrance AlarmCode1
    icon: mdi:numeric
    min: -1
    max: 9
    step: 1
    initial: -1
  hasp_displ_entrance_alarmcode2:
    name: displ_entrance AlarmCode2
    icon: mdi:numeric
    min: -1
    max: 9
    step: 1
    initial: -1
  hasp_displ_entrance_alarmcode3:
    name: displ_entrance AlarmCode3
    icon: mdi:numeric
    min: -1
    max: 9
    step: 1
    initial: -1
  hasp_displ_entrance_alarmcode4:
    name: displ_entrance AlarmCode4
    icon: mdi:numeric
    min: -1
    max: 9
    step: 1
    initial: -1

group:
  displ_entrance:
    name: displ_entrance
    entities:
      - binary_sensor.displ_entrance_connected
      - sensor.displ_entrance_status
      - light.displ_entrance_backlight
      - group.displ_entrance_pageselect
      - group.displ_entrance_colors
      - group.displ_entrance_automations
  displ_entrance_pageselect:
    name: displ_entrance Page Selection
    entities:
      - input_number.hasp_displ_entrance_activepage
      - input_number.hasp_displ_entrance_pagebutton1page
      - input_text.hasp_displ_entrance_pagebutton1label
      - input_number.hasp_displ_entrance_pagebutton2page
      - input_text.hasp_displ_entrance_pagebutton2label
      - input_number.hasp_displ_entrance_pagebutton3page
      - input_text.hasp_displ_entrance_pagebutton3label
      - input_number.hasp_displ_entrance_pagebutton4page
      - input_text.hasp_displ_entrance_pagebutton4label
  displ_entrance_automations:
    name: displ_entrance automations
    entities:
      - automation.hasp_displ_entrance_00_firsttimesetup

automation:
##############################################################################
# Run first time setup commands
  - alias: hasp_displ_entrance_00_FirstTimeSetup
    trigger: []
    action:
      - service: automation.trigger
        data:
          entity_id: 'automation.hasp_displ_entrance_00_automationgroupupdate'
      - service: homeassistant.turn_on
        data:
          entity_id: 'group.displ_entrance_automations'
      - service: input_text.set_value
        data:
          entity_id: 'input_text.hasp_displ_entrance_pagebutton1label'
          value: ''
      - service: input_text.set_value
        data:
          entity_id: 'input_text.hasp_displ_entrance_pagebutton2label'
          value: ''
      - service: input_text.set_value
        data:
          entity_id: 'input_text.hasp_displ_entrance_pagebutton3label'
          value: ''
      - service: input_text.set_value
        data:
          entity_id: 'input_text.hasp_displ_entrance_pagebutton4label'
          value: ''
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_displ_entrance_pagebutton1page'
          value: 1
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_displ_entrance_pagebutton2page'
          value: 4
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_displ_entrance_pagebutton3page'
          value: 3
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_displ_entrance_pagebutton4page'
          value: 5
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_displ_entrance_activepage'
          value: 1
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_displ_entrance_selectedforegroundcolor'
          value: 0
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_displ_entrance_selectedbackgroundcolor'
          value: 65535
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_displ_entrance_unselectedforegroundcolor'
          value: 65535
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_displ_entrance_unselectedbackgroundcolor'
          value: 25388

##############################################################################
# Set automation group members on start - Thanks @Nightcat!
  - alias: hasp_displ_entrance_00_AutomationGroupUpdate
    trigger:
    - platform: homeassistant
      event: start
    action:
    - service: group.set
      data_template:
        object_id: "displ_entrance_automations"
        entities: >-
          {%- for item in states.automation if ((item.entity_id | lower).startswith('automation.hasp_displ_entrance_')) -%}
          {{ item.entity_id }}
          {% if not loop.last %}, {% endif %}
          {%- endfor -%}


```
