### DISCUSSION TITLE
Saving the Background and Foreground Colours.

### DISCUSSION THREAD

**Discussion by Cjdavidson** [HASwitchPlate/HASPone#178] [General]
Is there any way to save the background and foreground colours. I have tried making a scene with the UI Scenes but when i recall them it only changes the backlight.

Any Help

**Comment by aderusha** [comment]
Try creating a scene with the 4 RGB lights used for the theme colors:

![image](https://user-images.githubusercontent.com/9554705/151668764-e31cb894-1cf9-4c43-b76b-c324e5d0323a.png)

**Reply by Cjdavidson** [reply]
<img width="974" alt="Screenshot 2022-01-31 at 11 31 05 am" src="https://user-images.githubusercontent.com/1190040/151786650-9c6ccdd8-d470-4021-8fd5-2d4aebf61d03.png">

Done that this is was is in the file scenes.yaml.

But it still does not work.

```
- id: '1643457277689'
  name: HASP Sitting Set Up
  entities:
    light.sitting_backlight:
      supported_color_modes:
      - brightness
      color_mode: brightness
      brightness: 26
      friendly_name: sitting backlight
      supported_features: 0
      state: 'on'
    number.sitting_active_page:
      min: 0
      max: 11
      step: 1
      mode: auto
      assumed_state: true
      icon: mdi:page-next-outline
      friendly_name: sitting active page
      state: '1'
    light.sitting_selected_foreground_color:
      supported_color_modes:
      - rgb
      color_mode: rgb
      brightness: 255
      hs_color:
      - 0
      - 0
      rgb_color:
      - 255
      - 255
      - 255
      xy_color:
      - 0.323
      - 0.329
      friendly_name: sitting selected foreground color
      supported_features: 0
      state: 'on'
    light.sitting_selected_background_color:
      supported_color_modes:
      - rgb
      color_mode: rgb
      brightness: 3
      hs_color:
      - 60
      - 38.039
      rgb_color:
      - 255
      - 255
      - 158
      xy_color:
      - 0.388
      - 0.43
      friendly_name: sitting selected background color
      supported_features: 0
      state: 'on'
    light.sitting_unselected_foreground_color:
      supported_color_modes:
      - rgb
      color_mode: rgb
      brightness: 255
      hs_color:
      - 0
      - 0
      rgb_color:
      - 255
      - 255
      - 255
      xy_color:
      - 0.323
      - 0.329
      friendly_name: sitting unselected foreground color
      supported_features: 0
      state: 'on'
    light.sitting_unselected_background_color:
      supported_color_modes:
      - rgb
      color_mode: rgb
      brightness: 3
      hs_color:
      - 0
      - 0
      rgb_color:
      - 255
      - 255
      - 255
      xy_color:
      - 0.323
      - 0.329
      friendly_name: sitting unselected background color
      supported_features: 0
      state: 'on'
  icon: fas:couch
```
Cameron
