### DISCUSSION TITLE
Combining dims on idle and dims on sun

### DISCUSSION THREAD

**Discussion by SylvainGa** [HASwitchPlate/HASPone#219] [Q&A]
Hi, in the bedroom, I've configured my V0.40 HASP device so at sun down, it would start to dim just like _dims with the sun_ but from 8pm to 6am, it acts like _dims on idle_. Would the following work?

Create an automation that triggers at 8pm and another one that triggers at 6am.

At 8pm, call the automation that dims on idle
At 6am, call the automation that dims with the sun

If not, is there a better option?

Thanks.

**Comment by SylvainGa** [comment]
So, gave it a go and it works when these are launched manually :-) I don't see a reason why they wouldn't work when launch at specific time.

```
alias: HASPone switch to dims on idle - Salle à manger
description: ""
trigger:
  - platform: time
    at: "20:00:00"
condition: []
action:
  - service: automation.turn_off
    data: {}
    target:
      entity_id: automation.haspone_dims_the_backlight_with_the_sun_salle_a_manger
  - service: automation.turn_on
    data: {}
    target:
      entity_id: >-
        automation.haspone_dim_the_display_screen_after_a_specified_period_of_inactivity_salle_a_manger
  - service: automation.trigger
    data:
      skip_condition: true
    target:
      entity_id: >-
        automation.haspone_dim_the_display_screen_after_a_specified_period_of_inactivity_salle_a_manger
mode: single
```

```
alias: HASPone switch to dims with the sun - Salle à manger
description: ""
trigger:
  - platform: time
    at: "06:00:00"
condition: []
action:
  - service: automation.turn_off
    data: {}
    target:
      entity_id: >-
        automation.haspone_dim_the_display_screen_after_a_specified_period_of_inactivity_salle_a_manger
  - service: automation.turn_on
    data: {}
    target:
      entity_id: automation.haspone_dims_the_backlight_with_the_sun_salle_a_manger
  - service: automation.trigger
    data:
      skip_condition: true
    target:
      entity_id: automation.haspone_dims_the_backlight_with_the_sun_salle_a_manger
mode: single
```

Seems pretty simple, let me know if there is a more _elegant_ way :-)

**Comment by aderusha** [comment]
Just triggering those automations manually isn't going to help too much,.  They both react to changes in the sun, so even if you do fire it off, anything they did will be overridden the next time the position of the sun changes.

Instead of triggering the automation manually at 8pm, **enable** the automation you want to be in control at that time and **disable** the other.

**Reply by SylvainGa** [reply]
Hi yes. that's exactly what I'm doing in the two automations I posted above. I'm also triggering them right away so I don't have to wait for their next trigger event.

For the dim with the sun automation. I also added the following feature in my V0.40 that I find convenient. The screen is dimmed only when all lights in a specified group are off. The idea here is if the room is artificially lit, there is no reason to dim to screen as it makes the display harder to read. Same for the dim on idle, it dims only when all lights in a specified group are off. As soon as you turn a light on, the screen returns to its non dimmed level. I never worked on blueprint before. I'll see how I can add these and do a push request if it's something you are interested in.

**Comment by SylvainGa** [comment]
Hi, if you have the time. can you tell what I'm doing wrong? I'm importing this blueprint that I created (based on your hasp_Dim_Screen_on_Idle.yaml)
https://github.com/SylvainGa/HABlueprints/blob/main/hasp_show_Screen_when_grouplight_is_on.yaml
But when I select Create automation, select my HASP device and group and save it, it doesn't show up in the Automation and this is what is written in the automation.yaml file

```
- id: '1670802650437'
  alias: HASPone Show the screen when a group of light is on - Salle à manger
  description: ''
  use_blueprint:
    path: SylvainGa/hasp_show_Screen_when_grouplight_is_on.yaml
    input:
      haspdevice: 262ca4d929de133aa9b6945658220c96
      lightgroup: group.lights_sallemanger
```

I don't know what I'm doing wrong :-(


Edit: I think I found my mistake, I was missing !input in the trigger,
