### DISCUSSION TITLE
Dim HASP backlight at night

### DISCUSSION THREAD

**Discussion by aderusha** [HASwitchPlate/HASPone#24] [Ideas]
I was looking to port over a legacy HASP automation to dim the backlight at night but then I remembered that there’s [a whole forum full of people making rad blueprints](https://community.home-assistant.io/c/blueprints-exchange/53)!

Check out [Dim lights based on the sun’s elevation](https://community.home-assistant.io/t/dim-lights-based-on-the-suns-elevation/269701), select your HASP backlight as the light to control and now the HASP won’t be shining bright at night in your bedroom.

**Comment by Cjdavidson** [comment]
Well I was using this to turn off my backlight on the old HASP plate and it worked nicely. But I tried on HASPone and it crashes. 

```
##############################################################################
# Automations and required components to enable "sleep mode" screen timeout.
##############################################################################
# Paste the following into your Lovelace config to control this via the UI:
##############################################################################
#      - type: entities
#        title: bedroom Screen Sleep
#        entities:
#          - entity: input_number.hasp_bedroom_sleeptime
#            name: Sleep timeout
#        show_header_toggle: false
##############################################################################

##############################################################################
input_number:
  hasp_bedroom_sleeptime:
    name: bedroom Sleep Mode Timeout in seconds
    icon: mdi:clock-end
    mode: box
    min: 0
    max: 9999
    step: 1
    unit_of_measurement: seconds

automation:
  ##############################################################################
  # Enable sleep timer
  - alias: hasp_bedroom_EnableSleepTime
    trigger:
      - platform: state
        entity_id: input_number.hasp_bedroom_sleeptime
      - platform: state
        entity_id: "binary_sensor.bedroom_connected"
        to: "on"
      - platform: homeassistant
        event: start
    condition:
      - condition: numeric_state
        entity_id: input_number.hasp_bedroom_sleeptime
        above: 0
    action:
      - service: mqtt.publish
        data_template:
          topic: "hasp/bedroom/command/json"
          payload_template: '["thup=1", "thsp={{states("input_number.hasp_bedroom_sleeptime")|int}}"]'

  ##############################################################################
  # Disable sleep timer
  - alias: hasp_bedroom_DisableSleepTime
    trigger:
      platform: state
      entity_id: input_number.hasp_bedroom_sleeptime
    condition:
      - condition: numeric_state
        entity_id: input_number.hasp_bedroom_sleeptime
        below: 1
    action:
      - service: mqtt.publish
        data_template:
          topic: "hasp/bedroom/command/json"
          payload: '["sleep=0", "thsp=0", "thup=0"]'
```
