### ISSUE TITLE
Dimmer slider issues

### ISSUE THREAD

**Issue by Gurulu-pc** [HASwitchPlate/HASPone#213]
Might be my configurations but when I slide the dimmer in home assistant, my HASPone slider moves accordingly and the light obeys. When i move the slider on the HASPone, nothing happens. So basically, the HASPone slider is only a status indicator instead of a control device. The dimmer is a DIY lamp I've built with esphome and a led strip. It's very strait forward PWM dimming from a wemo D1 mini. The dimmer was configured from the default blueprint from this repo (hasp_Display_Dimmer_with_Icon.yaml)
Software version : Home Assistant 2022.11.3, Supervisor 2022.10.2, Operating System 9.3
hardware: RPI3B+
here's the relevant automation.yaml entry :
```
- id: '1667772236417'
  alias: HASPone p[x].b[y] displays a dimmer with a toggle on/off icon
  description: ''
  use_blueprint:
    path: HASwitchPlate/hasp_Display_Dimmer_with_Icon.yaml
    input:
      font_select: 6 - Noto Sans 32
      haspdevice: 43f87b51c35fe9a31c395bb715839774
      haspbutton: 8
      dimmer: light.salle_de_bain
      text_on: Lum Pharmacie |
      ycen_select: 1 - Centered
      icon_off: 
      icon_on: 
      xcen_select: 2 - Right aligned
      hasppage: 4
```
Thanks for your help
