### ISSUE TITLE
Blueprint "HASP p[x].b[y] displays the current temperature with icon and colors" fails with temperature sensor

### ISSUE THREAD

**Issue by rebel7580** [HASwitchPlate/HASPone#95]
When creating an automation from this blueprint and selecting a temperature sensor instead of a weather provider, the automation fails. When saved, no "Run" is shown, and the automation does not show in the Automation list. The automations do show up in automations.yaml.

The homeassitant log shows the following ERRORs (tried twice with two different temperature sensors):

2021-05-03 16:19:26 ERROR (MainThread) [homeassistant.components.automation] Blueprint HASP p[x].b[y] displays the current temperature with icon and colors generated invalid automation with inputs OrderedDict([('haspdevice', 'cfc57889d19f2ce169bf924e4d916c67'), ('hasppage', 2), ('haspbutton', 5), ('temperature_sensor', 'sensor.outside_temp'), ('colortemp', True)]): Entity IDs can not be None for dictionary value @ data['entity_id']. Got None

2021-05-03 16:19:27 ERROR (MainThread) [homeassistant.components.automation] Blueprint HASP p[x].b[y] displays the current temperature with icon and colors generated invalid automation with inputs OrderedDict([('haspdevice', 'cfc57889d19f2ce169bf924e4d916c67'), ('hasppage', 2), ('haspbutton', 4), ('temperature_sensor', 'sensor.hotwater_am2301_temperature'), ('colortemp', True)]): Entity IDs can not be None for dictionary value @ data['entity_id']. Got None

When choosing a weather provider instead, the automation is successful and is shown inthe Automation list.

I know almost zero about blueprint/automation coding, but these lines in hasp_Display_Temperature_with_Icon_and_Colors.yaml look suspicious to me:

```
381: trigger:
382: - platform: state
383:   entity_id: !input 'weather_provider'
```

**Comment by rebel7580** [comment]
I'm definately a noobie when it comes to HA and yaml, so take this FWIW:

There seems to be two issues here:
1) the trigger for weather_provider will fail if no weather provider is defined,
2) there is no trigger for the temperature sensor, if defined. 

I tried this
```
trigger_variables:
   ...
  weather_provider: !input 'weather_provider'
  temperature_sensor: !input 'temperature_sensor'
  entityid: '{%- if temperature_sensor|lower == "none" -%}  {{- weather_provider -}} {%- else -%}  {{- temperature_sensor -}} {% endif %}'
trigger:
- platform: state
  entity_id: '{{ entityid }}'
```
but this causes an error also, probably based on mal-formed yaml on my part. The idea was to set 'entity_id' to either the weather entity or the temperature entity.

Of course, I may completely misunderstand this code!
